#docker ps: ktra xem có bnhiu container đang start
#curl -u elastic:admin123 localhost:9200: check container có chạy hay ko
#curl -u user:pass ip:port
#docker-compose up -d : chạy docker

version: '3.7'
#Định nghĩa các image cần pull về
#Để start docker chỉ định thì chạy docker-compose <tên service>
#Đế start all service thì chạy docker-compose up
services:
  #tên service(gì cũng đc)
  elasticsearch:
    #tên image muốn pull từ docker hub
    #image: ten_image:version
    image: elasticsearch:8.3.1
    #tên container docker
    container_name: elasticsearch
    #ánh xạ nơi lưu trữ docker và ổ đĩa
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    #port docker
    ports:
      - 9200:9200
      - 9300:9300
    #nơi định nghĩa môi trường
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      ELASTIC_PASSWORD: admin123
      xpack.security.enabled: "false"
      #xpack.security.enabled: "true"
    #networks đang sử dụng
    networks:
      - elk

  kibana:
    image: kibana:8.3.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: admin123
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: logstash:8.3.1
    container_name: logstash
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
      - ./logs:/usr/share/logstash/logs:ro,z
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch
    networks:
      - elk

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    depends_on:
      - logstash
    networks:
      - elk

volumes:
  setup:
  elastic_data:

networks:
  elk:
    driver: bridge